=== 1066mutex/gtec-demo-framework/DemoApps/Vulkan/UI/Declarative/Content/DeclarativeUI.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:annotation>
    <xs:documentation>
      Describes the Fsl.gen format
    </xs:documentation>
  </xs:annotation>

  <xs:simpleType name="_TP_LayoutOrientation">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Horizontal" />
      <xs:enumeration value="Vertical" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="_TP_ItemAlignment">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Near" />
      <xs:enumeration value="Center" />
      <xs:enumeration value="Far" />
      <xs:enumeration value="Stretch" />
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="_T_GridColumnDefinition">
    <xs:annotation>
      <xs:documentation></xs:documentation>
    </xs:annotation>
    <xs:attribute name="Width" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="_T_GridRowDefinition">
    <xs:annotation>
      <xs:documentation></xs:documentation>
    </xs:annotation>
    <xs:attribute name="Height" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:group name="_G_GridColumnDefinition">
    <xs:choice>
      <xs:element name="GridColumnDefinition" type="_T_GridColumnDefinition"/>
    </xs:choice>
  </xs:group>

  <xs:group name="_G_GridRowDefinition">
    <xs:choice>
      <xs:element name="GridRowDefinition" type="_T_GridRowDefinition"/>
    </xs:choice>
  </xs:group>


  <xs:group name="_G_GridColumnDefinitionList">
    <xs:sequence>
      <xs:group ref="_G_GridColumnDefinition" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:group>

  <xs:group name="_G_GridRowDefinitionList">
    <xs:sequence>
      <xs:group ref="_G_GridRowDefinition" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:group>


  <xs:complexType name="_T_GridLayoutColumnDefinitions">
    <xs:annotation>
      <xs:documentation></xs:documentation>
    </xs:annotation>
    <xs:group ref="_G_GridColumnDefinitionList"/>
  </xs:complexType>

  <xs:complexType name="_T_GridLayoutRowDefinitions">
    <xs:annotation>
      <xs:documentation></xs:documentation>
    </xs:annotation>
    <xs:group ref="_G_GridRowDefinitionList"/>
  </xs:complexType>


  <xs:group name="_G_GridColumnDefinitions">
    <xs:choice>
      <xs:element name="GridLayout.ColumnDefinitions" type="_T_GridLayoutColumnDefinitions"/>
    </xs:choice>
  </xs:group>

  <xs:group name="_G_GridRowDefinitions">
    <xs:choice>
      <xs:element name="GridLayout.RowDefinitions" type="_T_GridLayoutRowDefinitions"/>
    </xs:choice>
  </xs:group>

  <xs:group name="_G_GridLayoutColumnDefinitions">
    <xs:sequence>
      <xs:group ref="_G_GridColumnDefinitions" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:group>

  <xs:group name="_G_GridLayoutRowDefinitions">
    <xs:sequence>
      <xs:group ref="_G_GridRowDefinitions" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:group>

  <xs:group name="_G_GridContentList">
    <xs:sequence>
      <xs:group ref="_G_GridLayoutColumnDefinitions" minOccurs="0" maxOccurs="1"/>
      <xs:group ref="_G_GridLayoutRowDefinitions" minOccurs="0" maxOccurs="1"/>
      <xs:group ref="_G_WindowElement" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:group>


  <xs:complexType name="_T_GridLayout">
    <xs:annotation>
      <xs:documentation></xs:documentation>
    </xs:annotation>
    <xs:group ref="_G_GridContentList"/>
    <xs:attribute name="AlignmentX" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="AlignmentY" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="Name" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:complexType name="_T_FillLayout">
    <xs:annotation>
      <xs:documentation></xs:documentation>
    </xs:annotation>
    <xs:group ref="_G_WindowList"/>
    <xs:attribute name="AlignmentX" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="AlignmentY" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="Name" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:complexType name="_T_StackLayout">
    <xs:annotation>
      <xs:documentation></xs:documentation>
    </xs:annotation>
    <xs:group ref="_G_WindowList"/>
    <xs:attribute name="AlignmentX" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="AlignmentY" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="Orientation" type="_TP_LayoutOrientation" use="optional"/>
    <xs:attribute name="Name" type="xs:string" use="optional"/>
    <xs:attribute name="Spacing" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:complexType name="_T_UniformStackLayout">
    <xs:annotation>
      <xs:documentation></xs:documentation>
    </xs:annotation>
    <xs:group ref="_G_WindowList"/>
    <xs:attribute name="AlignmentX" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="AlignmentY" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="Orientation" type="_TP_LayoutOrientation" use="optional"/>
    <xs:attribute name="Name" type="xs:string" use="optional"/>
    <xs:attribute name="Spacing" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:complexType name="_T_UniformWrapLayout">
    <xs:annotation>
      <xs:documentation></xs:documentation>
    </xs:annotation>
    <xs:group ref="_G_WindowList"/>
    <xs:attribute name="AlignmentX" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="AlignmentY" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="Orientation" type="_TP_LayoutOrientation" use="optional"/>
    <xs:attribute name="Name" type="xs:string" use="optional"/>
    <!--<xs:attribute name="Spacing" type="xs:string" use="optional"/>-->
  </xs:complexType>

  <xs:complexType name="_T_WrapLayout">
    <xs:annotation>
      <xs:documentation></xs:documentation>
    </xs:annotation>
    <xs:group ref="_G_WindowList"/>
    <xs:attribute name="AlignmentX" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="AlignmentY" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="Orientation" type="_TP_LayoutOrientation" use="optional"/>
    <xs:attribute name="Name" type="xs:string" use="optional"/>
    <!--<xs:attribute name="Spacing" type="xs:string" use="optional"/>-->
  </xs:complexType>

  <xs:complexType name="_T_BackgroundWindow">
    <xs:annotation>
      <xs:documentation></xs:documentation>
    </xs:annotation>
    <xs:group ref="_G_WindowElement"/>
    <xs:attribute name="AlignmentX" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="AlignmentY" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="Name" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:complexType name="_T_LeftBar">
    <xs:annotation>
      <xs:documentation></xs:documentation>
    </xs:annotation>
    <xs:group ref="_G_WindowElement"/>
    <xs:attribute name="AlignmentX" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="AlignmentY" type="_TP_ItemAlignment" use="optional"/>
  </xs:complexType>

  <xs:complexType name="_T_TopBar">
    <xs:annotation>
      <xs:documentation></xs:documentation>
    </xs:annotation>
    <xs:group ref="_G_WindowElement"/>
    <xs:attribute name="AlignmentX" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="AlignmentY" type="_TP_ItemAlignment" use="optional"/>
  </xs:complexType>

  <xs:complexType name="_T_RightBar">
    <xs:annotation>
      <xs:documentation></xs:documentation>
    </xs:annotation>
    <xs:group ref="_G_WindowElement"/>
    <xs:attribute name="AlignmentX" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="AlignmentY" type="_TP_ItemAlignment" use="optional"/>
  </xs:complexType>

  <xs:complexType name="_T_BottomBar">
    <xs:annotation>
      <xs:documentation></xs:documentation>
    </xs:annotation>
    <xs:group ref="_G_WindowElement"/>
    <xs:attribute name="AlignmentX" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="AlignmentY" type="_TP_ItemAlignment" use="optional"/>
  </xs:complexType>

  <xs:complexType name="_T_Label">
    <xs:annotation>
      <xs:documentation></xs:documentation>
    </xs:annotation>
    <xs:attribute name="AlignmentX" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="AlignmentY" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="ContentAlignmentX" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="ContentAlignmentY" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="Content" type="xs:string" use="optional"/>

    <xs:attribute name="GridLayout.Column" type="xs:string" use="optional"/>
    <xs:attribute name="GridLayout.Row" type="xs:string" use="optional"/>
    <xs:attribute name="Name" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:complexType name="_T_SliderUInt8">
    <xs:annotation>
      <xs:documentation></xs:documentation>
    </xs:annotation>
    <xs:attribute name="AlignmentX" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="AlignmentY" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="Value" type="xs:string" use="optional"/>
    <xs:attribute name="Constraint" type="xs:string" use="optional"/>
    <xs:attribute name="Orientation" type="_TP_LayoutOrientation" use="optional"/>

    <xs:attribute name="GridLayout.Column" type="xs:string" use="optional"/>
    <xs:attribute name="GridLayout.Row" type="xs:string" use="optional"/>
    <xs:attribute name="Name" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:complexType name="_T_FmtValueLabelUInt8">
    <xs:annotation>
      <xs:documentation></xs:documentation>
    </xs:annotation>
    <xs:attribute name="AlignmentX" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="AlignmentY" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="ContentAlignmentX" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="ContentAlignmentY" type="_TP_ItemAlignment" use="optional"/>
    <xs:attribute name="Content" type="xs:string" use="optional"/>
    <xs:attribute name="Orientation" type="_TP_LayoutOrientation" use="optional"/>

    <xs:attribute name="GridLayout.Column" type="xs:string" use="optional"/>
    <xs:attribute name="GridLayout.Row" type="xs:string" use="optional"/>
    <xs:attribute name="Name" type="xs:string" use="optional"/>
  </xs:complexType>

  <xs:group name="_G_WindowElement">
    <xs:choice>
      <xs:element name="BackgroundWindow" type="_T_BackgroundWindow"/>
      <xs:element name="LeftBar" type="_T_LeftBar"/>
      <xs:element name="TopBar" type="_T_TopBar"/>
      <xs:element name="BottomBar" type="_T_BottomBar"/>
      <xs:element name="RightBar" type="_T_RightBar"/>
      <xs:element name="FillLayout" type="_T_FillLayout"/>
      <xs:element name="GridLayout" type="_T_GridLayout"/>
      <xs:element name="StackLayout" type="_T_StackLayout"/>
      <xs:element name="UniformStackLayout" type="_T_UniformStackLayout"/>
      <xs:element name="UniformWrapLayout" type="_T_UniformWrapLayout"/>
      <xs:element name="WrapLayout" type="_T_WrapLayout"/>
      <xs:element name="Label" type="_T_Label"/>
      <xs:element name="SliderUInt8" type="_T_SliderUInt8"/>
      <xs:element name="FmtValueLabelUInt8" type="_T_FmtValueLabelUInt8"/>
    </xs:choice>
  </xs:group>


  <xs:group name="_G_WindowList">
    <xs:sequence>
      <xs:group ref="_G_WindowElement" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:group>


  <xs:group name="_G_BaseWindowElement">
    <xs:choice>
      <xs:element name="FillLayout" type="_T_FillLayout"/>
    </xs:choice>
  </xs:group>

  <xs:complexType name="_T_BaseWindow">
    <xs:annotation>
    </xs:annotation>
    <xs:group ref="_G_BaseWindowElement"/>
  </xs:complexType>

  <xs:group name="_G_RootElement">
    <xs:choice>
      <xs:element name="FillLayout" type="_T_FillLayout"/>
    </xs:choice>
  </xs:group>

  <xs:complexType name="_T_DeclarativeUITest">
    <xs:group ref="_G_RootElement"/>
  </xs:complexType>

  <xs:element name="DeclarativeUITest" type="_T_DeclarativeUITest"/>
</xs:schema>

=== 1066mutex/gtec-demo-framework/DemoApps/GLES3/UI/Declarative/Content/DeclarativeUI.xml
<?xml version="1.0" encoding="UTF-8"?>
<DeclarativeUITest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="DeclarativeUI.xsd">
  <FillLayout>
    <BackgroundWindow AlignmentX="Near" theme_Type="DialogNormal">
      <StackLayout Orientation="Horizontal" Spacing="20">
        <Label Content="Hey"/>
        <SliderUInt32 theme_Orientation="Vertical" Value="255" theme_Constraint="0,1000" AlignmentX="Center" AlignmentY="Stretch" MinHeight="200" />
        <StackLayout>
          <Label Content="One way binding with conversion"/>
          <GridLayout AlignmentX="Stretch">
            <GridLayout.ColumnDefinitions>
              <GridColumnDefinition Width="Auto"/>
              <GridColumnDefinition Width="4"/>
              <GridColumnDefinition Width="300"/>
              <GridColumnDefinition Width="Auto"/>
              <GridColumnDefinition Width="34"/>
            </GridLayout.ColumnDefinitions>
            <GridLayout.RowDefinitions>
              <GridRowDefinition Height="Auto"/>
              <GridRowDefinition Height="Auto"/>
              <GridRowDefinition Height="Auto"/>
              <GridRowDefinition Height="Auto"/>
            </GridLayout.RowDefinitions>
            <Label Content="Red:" AlignmentY="Center" GridLayout.Column="0" GridLayout.Row="0"/>
            <Label Content="G:" AlignmentY="Center" GridLayout.Column="0" GridLayout.Row="1"/>
            <Label Content="B:" AlignmentY="Center" GridLayout.Column="0" GridLayout.Row="2"/>
            <Label Content="A:" AlignmentY="Center" GridLayout.Column="0" GridLayout.Row="3"/>
            <SliderUInt8 Orientation="Horizontal" Value="255" theme_Constraint="0,255" Name="ColorSliderR" GridLayout.Column="2" GridLayout.Row="0"/>
            <SliderUInt8 Orientation="Horizontal" Value="255" theme_Constraint="0,255" Name="ColorSliderG" GridLayout.Column="2" GridLayout.Row="1"/>
            <SliderUInt8 Orientation="Horizontal" Value="255" theme_Constraint="0,255" Name="ColorSliderB" GridLayout.Column="2" GridLayout.Row="2"/>
            <SliderUInt8 Orientation="Horizontal" Value="255" theme_Constraint="0,255" Name="ColorSliderA" GridLayout.Column="2" GridLayout.Row="3"/>

            <FmtValueLabelUInt8 ContentAlignmentX="Far" AlignmentY="Center" GridLayout.Column="4" GridLayout.Row="0" Content="{Binding ElementName=ColorSliderR,Path=Value}"/>
            <FmtValueLabelUInt8 ContentAlignmentX="Far" AlignmentY="Center" GridLayout.Column="4" GridLayout.Row="1" Content="{Binding ElementName=ColorSliderG,Path=Value}"/>
            <FmtValueLabelUInt8 ContentAlignmentX="Far" AlignmentY="Center" GridLayout.Column="4" GridLayout.Row="2" Content="{Binding ElementName=ColorSliderB,Path=Value}"/>
            <FmtValueLabelUInt8 ContentAlignmentX="Far" AlignmentY="Center" GridLayout.Column="4" GridLayout.Row="3" Content="{Binding ElementName=ColorSliderA,Path=Value}"/>
          </GridLayout>
          <Label Content="G:" AlignmentX="Center" AlignmentY="Center"/>
          <FmtValueLabelUInt8 AlignmentX="Center" AlignmentY="Center" Name="Hey" Content="{Binding ElementName=ColorSliderG,Path=Value}"/>
          <FmtValueLabelUInt8 AlignmentX="Far" AlignmentY="Center" Content="{Binding ElementName=Hey,Path=Content}"/>
          <FmtValueLabelUInt8 AlignmentX="Near" AlignmentY="Center" Content="{Binding ElementName=Hey,Path=Content}"/>
          <Label Content="Control" AlignmentX="Center" AlignmentY="Center"/>
        </StackLayout>
      </StackLayout>
    </BackgroundWindow>
    <BackgroundWindow AlignmentX="Far"  theme_Type="DialogTransparent">
      <StackLayout Orientation="Vertical">
        <UniformStackLayout Orientation="Horizontal">
          <TextButton Content="Five" AlignmentX="Stretch"/>
          <OutlinedTextButton Content="Jumping" AlignmentX="Stretch"/>
          <ContainedTextButton Content="Wizard" AlignmentX="Stretch"/>
        </UniformStackLayout>
        <UniformStackLayout Orientation="Horizontal">
          <TextButton Content="Five" AlignmentX="Center"/>
          <OutlinedTextButton Content="Jumping" AlignmentX="Center"/>
          <ContainedTextButton Content="Wizard" AlignmentX="Center"/>
        </UniformStackLayout>
        <Divider/>
        <UniformStackLayout Orientation="Horizontal">
          <CheckBox Text="Five" AlignmentX="Stretch" Enabled="false"/>
          <CheckBox Text="Jumping" AlignmentX="Stretch" Checked="true"/>
          <CheckBox Text="Wizard" AlignmentX="Stretch"/>
        </UniformStackLayout>
        <UniformStackLayout Orientation="Horizontal">
          <RadioButton GroupName="Test" Text="Five" AlignmentX="Stretch" Enabled="false"/>
          <RadioButton GroupName="Test" Text="Jumping" AlignmentX="Stretch" Checked="true"/>
          <RadioButton GroupName="Test" Text="Wizard" AlignmentX="Stretch"/>
        </UniformStackLayout>
        <UniformStackLayout Orientation="Horizontal">
          <Switch Text="Five" AlignmentX="Stretch" Enabled="false"/>
          <Switch Text="Jumping" AlignmentX="Stretch" Checked="true"/>
          <Switch Text="Wizard" AlignmentX="Stretch"/>
        </UniformStackLayout>
        <Divider/>
        <FloatingButton theme_Type="Back"/>
      </StackLayout>
    </BackgroundWindow>

    <ScrollViewer AlignmentX="Center" AlignmentY="Stretch" ScrollMode="TranslateY">
      <StackLayout Orientation="Vertical">
        <Label Content="1" AlignmentX="Center"/>
        <Label Content="2" AlignmentX="Center"/>
        <Label Content="3" AlignmentX="Center"/>
        <Label Content="4" AlignmentX="Center"/>
        <Label Content="5" AlignmentX="Center"/>
        <Label Content="6" AlignmentX="Center"/>
        <Label Content="7" AlignmentX="Center"/>
        <Label Content="8" AlignmentX="Center"/>
        <Label Content="9" AlignmentX="Center"/>
        <Label Content="*** Drag this to scroll ***"/>
        <Label Content="1" AlignmentX="Center"/>
        <Label Content="2" AlignmentX="Center"/>
        <Label Content="3" AlignmentX="Center"/>
        <Label Content="4" AlignmentX="Center"/>
        <Label Content="5" AlignmentX="Center"/>
        <Label Content="6" AlignmentX="Center"/>
        <Label Content="7" AlignmentX="Center"/>
        <Label Content="8" AlignmentX="Center"/>
        <Label Content="9" AlignmentX="Center"/>
        <Label Content="*** Drag this to scroll ***"/>
        <Label Content="1" AlignmentX="Center"/>
        <Label Content="2" AlignmentX="Center"/>
        <Label Content="3" AlignmentX="Center"/>
        <Label Content="4" AlignmentX="Center"/>
        <Label Content="5" AlignmentX="Center"/>
        <Label Content="6" AlignmentX="Center"/>
        <Label Content="7" AlignmentX="Center"/>
        <Label Content="8" AlignmentX="Center"/>
        <Label Content="9" AlignmentX="Center"/>
        <Label Content="*** Drag this to scroll ***"/>
        <Label Content="1" AlignmentX="Center"/>
        <Label Content="2" AlignmentX="Center"/>
        <Label Content="3" AlignmentX="Center"/>
        <Label Content="4" AlignmentX="Center"/>
        <Label Content="5" AlignmentX="Center"/>
        <Label Content="6" AlignmentX="Center"/>
        <Label Content="7" AlignmentX="Center"/>
        <Label Content="8" AlignmentX="Center"/>
        <Label Content="9" AlignmentX="Center"/>
        <Label Content="*** Drag this to scroll ***"/>
        <Label Content="1" AlignmentX="Center"/>
        <Label Content="2" AlignmentX="Center"/>
        <Label Content="3" AlignmentX="Center"/>
        <Label Content="4" AlignmentX="Center"/>
        <Label Content="5" AlignmentX="Center"/>
        <Label Content="6" AlignmentX="Center"/>
        <Label Content="7" AlignmentX="Center"/>
        <Label Content="8" AlignmentX="Center"/>
        <Label Content="9" AlignmentX="Center"/>
        <Label Content="*** Drag this to scroll ***"/>
        <Label Content="1" AlignmentX="Center"/>
        <Label Content="2" AlignmentX="Center"/>
        <Label Content="3" AlignmentX="Center"/>
        <Label Content="4" AlignmentX="Center"/>
        <Label Content="5" AlignmentX="Center"/>
        <Label Content="6" AlignmentX="Center"/>
        <Label Content="7" AlignmentX="Center"/>
        <Label Content="8" AlignmentX="Center"/>
        <Label Content="9" AlignmentX="Center"/>
        <Label Content="*** Drag this to scroll ***"/>
        <Label Content="1" AlignmentX="Center"/>
        <Label Content="2" AlignmentX="Center"/>
        <Label Content="3" AlignmentX="Center"/>
        <Label Content="4" AlignmentX="Center"/>
        <Label Content="5" AlignmentX="Center"/>
        <Label Content="6" AlignmentX="Center"/>
        <Label Content="7" AlignmentX="Center"/>
        <Label Content="8" AlignmentX="Center"/>
        <Label Content="9" AlignmentX="Center"/>
        <Label Content="*** Drag this to scroll ***"/>
        <Label Content="1" AlignmentX="Center"/>
        <Label Content="2" AlignmentX="Center"/>
        <Label Content="3" AlignmentX="Center"/>
        <Label Content="4" AlignmentX="Center"/>
        <Label Content="5" AlignmentX="Center"/>
        <Label Content="6" AlignmentX="Center"/>
        <Label Content="7" AlignmentX="Center"/>
        <Label Content="8" AlignmentX="Center"/>
        <Label Content="9" AlignmentX="Center"/>
        <Label Content="*** Drag this to scroll ***"/>
      </StackLayout>
    </ScrollViewer>


    <StackLayout AlignmentX="Stretch" AlignmentY="Far" Spacing="4">
      <Label Content="UniformWrapLayout"/>
      <UniformWrapLayout Orientation="Horizontal" AlignmentX="Center" AlignmentY="Far" >
        <Label Content="0. The quick brown fox jumps over the lazy dog"/>
        <Label Content="1. A long string."/>
        <Label Content="2. A longer string."/>
        <Label Content="3. A even longer string."/>
        <Label Content="4. A even longer string."/>
        <Label Content="5. A even longer string."/>
        <Label Content="6. A even longer string."/>
